import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8001"     # Backend endpoint



st.set_page_config(
    page_title = "Travel Planner Agentic Application",
    # page_icon = "",
    layout = "centered",
    initial_sidebar_state="expanded",
)

st.title("Travel Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages= []

st.header("How can I help you in planning a trip ? Let me know where do you want to visit.")

# --- SIDEBAR DEBUG SETTINGS ---
st.sidebar.title("Developer Tools")
debug_mode = st.sidebar.checkbox("Enable Debug Mode", value=False)

with st.form(key = "Query_form", clear_on_submit= True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        ## Show user message
        # Show thinking spinner while backend processes
        with st.spinner("Bot is thinking..."):
            payload = {"query": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)
            
            # --- DEBUG BLOCK ---
            if debug_mode:
                st.subheader("DEBUG: Backend Response")
                st.json(response.json()) # This shows exactly what the backend sent
            # --------------------

        if response.status_code ==200:
            answer = response.json().get("answer", "No answer returned.")
            # markdown_content = f"""# AI Travel Plan

            # # ** Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # # ** Created by:** Atriyo's Travel Agent

            # ---

            # {answer}
          
            # ---

            # * This travel plan was generated by AI. Please verify all information, especially prices, operating prices.

            # """
            st.markdown(answer)
        else:
            st.error(f"Backend Error: {response.text}")

    except Exception as e:
        raise Exception(f"The response failed due to {e}") from e
